import fs from "fs";
import dotenv from "dotenv";
dotenv.config();
const acsessToken = process.env.META_ACCESS_TOKEN;
async function getMetaAds(competitorMetaId) {
  try {
    const url = new URL("https://graph.facebook.com/v18.0/ads_archive");
    const countryCodes = [
      "ALL",
      "BR",
      "IN",
      "GB",
      "US",
      "CA",
      "AR",
      "AU",
      "AT",
      "BE",
      "CL",
      "CN",
      "CO",
      "HR",
      "DK",
      "DO",
      "EG",
      "FI",
      "FR",
      "DE",
      "GR",
      "HK",
      "ID",
      "IE",
      "IL",
      "IT",
      "JP",
      "JO",
      "KW",
      "LB",
      "MY",
      "MX",
      "NL",
      "NZ",
      "NG",
      "NO",
      "PK",
      "PA",
      "PE",
      "PH",
      "PL",
      "RU",
      "SA",
      "RS",
      "SG",
      "ZA",
      "KR",
      "ES",
      "SE",
      "CH",
      "TW",
      "TH",
      "TR",
      "AE",
      "VE",
      "PT",
      "LU",
      "BG",
      "CZ",
      "SI",
      "IS",
      "SK",
      "LT",
      "TT",
      "BD",
      "LK",
      "KE",
      "HU",
      "MA",
      "CY",
      "JM",
      "EC",
      "RO",
      "BO",
      "GT",
      "CR",
      "QA",
      "SV",
      "HN",
      "NI",
      "PY",
      "UY",
      "PR",
      "BA",
      "PS",
      "TN",
      "BH",
      "VN",
      "GH",
      "MU",
      "UA",
      "MT",
      "BS",
      "MV",
      "OM",
      "MK",
      "LV",
      "EE",
      "IQ",
      "DZ",
      "AL",
      "NP",
      "MO",
      "ME",
      "SN",
      "GE",
      "BN",
      "UG",
      "GP",
      "BB",
      "AZ",
      "TZ",
      "LY",
      "MQ",
      "CM",
      "BW",
      "ET",
      "KZ",
      "NA",
      "MG",
      "NC",
      "MD",
      "FJ",
      "BY",
      "JE",
      "GU",
      "YE",
      "ZM",
      "IM",
      "HT",
      "KH",
      "AW",
      "PF",
      "AF",
      "BM",
      "GY",
      "AM",
      "MW",
      "AG",
      "RW",
      "GG",
      "GM",
      "FO",
      "LC",
      "KY",
      "BJ",
      "AD",
      "GD",
      "VI",
      "BZ",
      "VC",
      "MN",
      "MZ",
      "ML",
      "AO",
      "GF",
      "UZ",
      "DJ",
      "BF",
      "MC",
      "TG",
      "GL",
      "GA",
      "GI",
      "CD",
      "KG",
      "PG",
      "BT",
      "KN",
      "SZ",
      "LS",
      "LA",
      "LI",
      "MP",
      "SR",
      "SC",
      "VG",
      "TC",
      "DM",
      "MR",
      "AX",
      "SM",
      "SL",
      "NE",
      "CG",
      "AI",
      "YT",
      "CV",
      "GN",
      "TM",
      "BI",
      "TJ",
      "VU",
      "SB",
      "ER",
      "WS",
      "AS",
      "FK",
      "GQ",
      "TO",
      "KM",
      "PW",
      "FM",
      "CF",
      "SO",
      "MH",
      "VA",
      "TD",
      "KI",
      "ST",
      "TV",
      "NR",
      "RE",
      "LR",
      "ZW",
      "CI",
      "MM",
      "AN",
      "AQ",
      "BQ",
      "BV",
      "IO",
      "CX",
      "CC",
      "CK",
      "CW",
      "TF",
      "GW",
      "HM",
      "XK",
      "MS",
      "NU",
      "NF",
      "PN",
      "BL",
      "SH",
      "MF",
      "PM",
      "SX",
      "GS",
      "SS",
      "SJ",
      "TL",
      "TK",
      "UM",
      "WF",
      "EH",
    ];

    const params = {
      access_token: acsessToken,
      search_page_ids: competitorMetaId,
      ad_reached_countries: countryCodes,
      fields: [
        "id",
        "page_name",
        "ad_creation_time",
        "ad_delivery_start_time",
        "ad_delivery_stop_time",
        "ad_snapshot_url",
        "publisher_platforms",
        "ad_creative_bodies",
        "ad_creative_link_captions",
        "ad_creative_link_descriptions",
        "age_country_gender_reach_breakdown",
        "delivery_by_region",
        "eu_total_reach",
        "estimated_audience_size",
        "demographic_distribution",
        "impressions",
        "spend",
        "target_ages",
        "target_gender",
        "target_locations",
      ].join(","),
      limit: "250",
    };

    console.log("İstek gönderiliyor...");
    url.search = new URLSearchParams(params).toString();
    // console.log("url: ", url);
    const response = await fetch(url);

    if (!response.ok) {
      const errorData = await response.json();
      console.error("API Hata Detayları:", JSON.stringify(errorData, null, 2));
      throw new Error(
        `API Hatası: ${errorData?.error?.message || "Bilinmeyen hata"}`
      );
    }

    const data = await response.json();

    // Sonuçları daha okunaklı formatta göster
    if (data.data && data.data.length > 0) {
      console.log(`\nToplam ${data.data.length} reklam bulundu.\n`);
      //   console.log(data);
      //   console.log(data.data);
      //   console.log("AGE-GENDER", data.data.target_locations);

      // Verileri test.json dosyasına kaydet

      // fs.writeFileSync("testGps.json", JSON.stringify(data.data, null, 2));
      // console.log("Veriler test.json dosyasına kaydedildi.");
    } else {
      console.log("Hiç reklam bulunamadı.");
    }

    return data;
  } catch (error) {
    console.error("Hata:", error.message);
    throw error;
  }
}

// Fonksiyonu çağır
// getMetaAds().catch((error) => {
//   console.error("İşlem başarısız:", error.message);
// });

export default getMetaAds;
